# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Raum für ihr Recht
description: ""
author: "Niels Nübel"
baseurl: ""
url: "http://joverrides.niels-nuebel.de"
googleanalyticss:  UA-83736439-1

# Build settings
markdown: kramdown

#Exclude Files or Folder
exclude: [node_modules, gulpfile.js, package.json, bower_components, bower.json, Gemfile, Gemfile.lock, CNAME]
sass:
  sass_dir: _sass
  style: compressed

repository: nielsnuebel/joverrides